### ISSUE TITLE
Rename `ToUnderscore` to `ToSnakeCase`

### ISSUE THREAD

**Issue by huandu** [huandu/xstrings#3]
See [Snake case](http://en.wikipedia.org/wiki/Snake_case).

**Comment by athom** [comment]
will be better to keep it as alias :)

**Comment by huandu** [comment]
@athom "underscore string" makes no sense. It's a typical Chinglish. I think it's not worth keeping it. :)

**Comment by athom** [comment]
don't think it is Chinglish
http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore

**Comment by huandu** [comment]
It's not good to keep two functions doing exactly the same thing. It will confuse library users. It's muh better to choose one carefully and use it forever.

Back to the naming issue, "snake case" is better obviously. There is a wikipedia page defining this kind of string as "snake case" string while there is none for "underscore string" or "underscore case".

RoR may have a good reason to use "underscore" as method name. However, it just one special case. There are also many libraries uses term "snake case" like [String#snake_case](http://www.rubydoc.info/gems/extlib/0.9.15/String#snake_case-instance_method). Wikipedia page is more preferred than these special cases.
