### ISSUE TITLE
xstrings imports testing

### ISSUE THREAD

**Issue by heavenlyhash** [huandu/xstrings#33]
xstrings currently imports the `testing` package: https://godoc.org/github.com/huandu/xstrings?import-graph

This is kind of a bummer for consumers further downstream, because it causes the inclusion of all sorts of stuff like `runtime/pprof`, which will bloat the final binaries for any user of the library.

It looks like this is just because `testing` is imported in `test.go`... which look like is just providing helper functions for testing, so moving it into the testing namespaces by moving the file to e.g. `util_test.go` should fix this.

**Comment by huandu** [comment]
Thanks for raising this issue to me. I'll use your solution to fix this issue.
