### ISSUE TITLE
CamelCase and capital input

### ISSUE THREAD

**Issue by jhayotte** [huandu/xstrings#34]
Hi,

```
func TestToCamelCase(t *testing.T) {
	runTestCases(t, ToCamelCase, _M{
		"GOLANG":             "Golang",
	})
}
```
The following test should succeed instead it returns "GOLANG". 

```
--- FAIL: TestToCamelCase (0.00s)
        util_test.go:22: case fails. [case:GOLANG]
                should => "Golang"
                actual => "GOLANG"
```

Is it a wanted behavior?

Cheers,

**Comment by huandu** [comment]
It's reasonable to convert "GOLANG" to "Golang" in `ToCamelCase`. And "GOLANG_IS_GREAT" should be converted to "GolangIsGreat" if we support formal one.

**Comment by jhayotte** [comment]
Thanks @huandu !
I would add in convert_test.go this new use case.
