### ISSUE TITLE
ToSnakeCase should handle numbers as well

### ISSUE THREAD

**Issue by maroux** [huandu/xstrings#39]
Expect both `ToSnakeCase("http2xx")` and `ToSnakeCase("HTTP2XX")` to generate `http_2xx`.

Currently, the former (lowercase) returns `http2xx` and the latter `htt_p2_xx` 😕

**Comment by huandu** [comment]
Sorry for late response. This issue was out of my radar.

It's a reasonable but also a breaking change to `ToSnakeCase` api. I'll think of a way to make sure this change won't break too many existing cases.
