### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by rarkins** [huandu/xstrings#42]
Can there be a new version released that includes the kebab strings feature?

It's used here: https://github.com/Masterminds/sprig/blob/9f8fceff796fb9f4e992cd2bece016be0121ab74/functions.go#L132

And I'm seeing some cases where Go Modules users get install failures because v1.0.0 of this repo is being installed.

**Comment by huandu** [comment]
Ah, I forgot to tag it. I'll do it right now. Thanks for your reminder.

**Comment by huandu** [comment]
@rarkins `ToKebabCase` is included in v1.2.0. Check it out.

**Comment by rarkins** [comment]
@huandu thanks, I see that v1.0.0 was a release while v1.1.0 and v1.2.0 were just tags - so I missed them. I think the "go get" failures I'm seeing may be because `Masterminds/sprig` hasn't embraced go modules yet.
