### ISSUE TITLE
ToCamelCase handles spaces as word connector

### ISSUE THREAD

**Issue by Ilyes512** [huandu/xstrings#45]
Shouldn't the `ToCamelCase` handle spaces?

When you use `hello world` as the input to `ToCamelCase` you get `Hello world`. I was expecting to see `HelloWorld` instead. Looking at `ToKebab` and `ToSnakeCase` I did get the expected results: `hello-world` and `hello_world` .

One way I can get the behaviour I want is to do ` ToCamelCase(toSnakeCase("hello world"))`.

**Comment by huandu** [comment]
It's an undefined behavior in `ToCamelCase`. As this function was designed for variable name conversion, e.g. `get_key` to `GetKey`, space is not expected in the source string.

We can define this behavior just like what you suggested. See #1 for new rules.
