### ISSUE TITLE
Add xstrings.Join(sep string, s ...string) string

### ISSUE THREAD

**Issue by renom** [huandu/xstrings#51]
The idea is from C# (String.Join)

**Comment by huandu** [comment]
There is [Join](https://pkg.go.dev/strings#Join) in Go standard package.

**Comment by renom** [comment]
I mean, adding a Join function with a different syntax so that it could be used like:
`xstrings.Join(" ", "A", "B", "C") // returns "A B C"`

**Comment by renom** [comment]
Also, adding a Join function that ignores empty values could also be useful.

**Comment by huandu** [comment]
I review the document for [C# String.Join method](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=net-6.0). There is no variadic parameters in all method signatures. The C#-style join method looks quite similar to the Go-style join, `String.Join(String sep, String[] values)` vs `strings.Join(values []string, sep string)`. I don't think it's necessary to add a new API for your scenario.

> Also, adding a Join function that ignores empty values could also be useful.
Regarding to this feature request, it may not be feasible. There is no "nil string" or "invalid empty string" in Go. As a package for all use cases, there is no reliable way to guess whether an empty string  should be omitted or not.

**Comment by huandu** [comment]
Close this issue as there's no more update for days. Feel free to reopen it if you have more thoughts. @renom
