### ISSUE TITLE
`ToCamelCase` does not recognize and capital letter as a work break

### ISSUE THREAD

**Issue by dbainbri-ciena** [huandu/xstrings#54]
When using `ToCamelCase` on a string that is already camel case all but the first rune are lower cased.

i.e., `ToCamelCase('OneTwoThree')` ==> `Onetwothree`

I expected this to yield `OneTwoThree`.

**Comment by huandu** [comment]
It sounds reasonable. The RoR's `String#camelize` method does handle the case in this way.

This change may be a breaking change to existing users. I'll release this change as a new feature rather than a bug.
