### ISSUE TITLE
ToCamelCase returns PascalCase

### ISSUE THREAD

**Issue by LlewellynS96** [huandu/xstrings#56]
The first letter in camelCase should be lower case, e.g. `httpServer`. This is discussed in many places on the internet, including [here](https://stackoverflow.com/questions/41768733/camel-case-and-pascal-case-mistake).

This results in bugs in downstream packages like [this one](https://github.com/Masterminds/sprig/issues/328) in `sprig`.

I believe the solution might be to remove one line and fix the tests.

https://github.com/huandu/xstrings/blob/6ae33fe8028ca830b1d07eebeee74e2399b5027e/convert.go#L36

**Comment by huandu** [comment]
Make sense. I'll add a new api `ToPascalCase` and change `ToCamelCase` behavior.
